In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# import libraries
import csv
import torch
import pandas as pd

In [3]:
# set data path
Data_path = "/content/drive/MyDrive/Colab Notebooks/LinkedIn Learning/01_Hands-On PyTorch Machine Learning Explore the capabilities of PyTorch/Tutors.csv"

In [4]:
# read the top 50 rows of the csv file into a pandas dataframe
# install Pandas library: pip3 install pandas
df = pd.read_csv(Data_path,nrows=50)

In [5]:
# display the pandas dataframe
display(df)

,username,name,gender,Address,stateZip,email,sessions
0,user1,John Doe,Male,123 Main St,CA 90001,johndoe@example.com,3
1,user2,Jane Smith,Female,456 Oak St,NY 10001,janesmith@example.com,7
2,user3,Michael Johnson,Male,789 Maple St,TX 77001,michaelj@example.com,10
3,user4,Emily Brown,Female,135 Elm St,IL 60601,emilybrown@example.com,4
4,user5,Christopher Wilson,Male,246 Pine St,PA 19101,chriswilson@example.com,2
5,user6,Elizabeth Johnson,Female,369 Cedar St,GA 30301,lizjohnson@example.com,9
6,user7,James Anderson,Male,482 Birch St,FL 33101,jamesanderson@example.com,5
7,user8,Patricia Taylor,Female,159 Cherry St,NC 28201,patriciataylor@example.com,1
8,user9,Robert Thomas,Male,891 Redwood St,OH 44101,robertthomas@example.com,8
9,user10,Jennifer Jackson,Female,111 Ash St,MI 48201,jenniferjackson@example.com,6
10,user11,William Martinez,Male,234 Magnolia St,VA 23201,williammartinez@example.com,3
11,user12,Linda Harris,Female,357 Dogwood St,MA 02101,lindaharris@example.com,4
12,user13,Richard Smith,Male,369 Holly St,WA 98101,richardsmith@example.com,7
13,user14,Barbara Lee,Female,123 Spruce St,CO 80201,barbaralee@example.com,2
14,user15,Joseph Walker,Male,456 Apple St,AZ 85001,josephwalker@example.com,6
15,user16,Susan Hall,Female,789 Orange St,NJ 07101,susanhall@example.com,9
16,user17,Charles Brown,Male,135 Fig St,IN 46201,charlesbrown@example.com,1
17,user18,Mary Davis,Female,246 Olive St,TN 37201,marydavis@example.com,5
18,user19,Thomas Jackson,Male,369 Pear St,MO 64101,thomasjackson@example.com,8
19,user20,Karen Thompson,Female,482 Peach St,MD 21201,karenthompson@example.com,10
20,user21,David White,Male,159 Almond St,WI 53201,davidwhite@example.com,3
21,user22,Carol Garcia,Female,891 Cherry St,AL 36101,carolgarcia@example.com,7
22,user23,Daniel Rodriguez,Male,111 Plum St,SC 29201,danielrodriguez@example.com,4
23,user24,Sharon Young,Female,234 Persimmon St,LA 70101,sharonyoung@example.com,6
24,user25,Paul Hernandez,Male,357 Apricot St,KY 40201,paulhernandez@example.com,2
25,user26,Diane Hall,Female,369 Grape St,OR 97201,dianehall@example.com,9
26,user27,Mark Lee,Male,482 Blackberry St,OK 73101,marklee@example.com,5
27,user28,Nancy Perez,Female,159 Raspberry St,CT 06101,nancyperez@example.com,1
28,user29,Donald Lewis,Male,891 Strawberry St,IA 50301,donaldlewis@example.com,8
29,user30,Michelle Robinson,Female,111 Blueberry St,MS 39201,michellerobinson@example.com,10
30,user31,George Clark,Male,234 Currant St,AR 72201,georgeclark@example.com,3
31,user32,Laura Nelson,Female,357 Raisin St,KS 67201,lauranelson@example.com,4
32,user33,Kenneth Mitchell,Male,369 Cranberry St,UT 84101,kennethmitchell@example.com,7
33,user34,Rebecca Carter,Female,482 Fig St,NV 89101,rebeccacarter@example.com,2
34,user35,Stephen Phillips,Male,159 Nectarine St,NE 68101,stephenphillips@example.com,6
35,user36,Kathleen Evans,Female,891 Tangerine St,NM 87101,kathleenevans@example.com,9
36,user37,Edward Turner,Male,111 Mandarin St,ME 04101,edwardturner@example.com,1
37,user38,Judith Torres,Female,234 Clementine St,RI 02901,judithtorres@example.com,5
38,user39,Brian Murphy,Male,357 Grapefruit St,ID 83701,brianmurphy@example.com,8
39,user40,Deborah Collins,Female,369 Lime St,NH 03101,deborahcollins@example.com,10
40,user41,Ronald Jenkins,Male,482 Lemon St,SD 57101,ronaldjenkins@example.com,3
41,user42,Dorothy Bailey,Female,159 Melon St,ND 58101,dorothybailey@example.com,7
42,user43,Larry Rivera,Male,891 Cantaloupe St,MT 59101,larryrivera@example.com,4
43,user44,Shirley Cooper,Female,111 Watermelon St,DE 19901,shirleycooper@example.com,6
44,user45,Kevin Watson,Male,234 Honeydew St,VT 05401,kevinwatson@example.com,2
45,user46,Pamela Foster,Female,357 Kiwi St,AK 99501,pamelafoster@example.com,9
46,user47,Raymond Gray,Male,369 Mango St,HI 96801,raymondgray@example.com,5
47,user48,Gloria Bryant,Female,482 Papaya St,WV 25301,gloriabryant@example.com,1
48,user49,Alan Powell,Male,159 Grape St,WY 82001,alanpowell@example.com,8
49,user50,Lisa Simmons,Female,891 Pineapple St,DC 20001,lisasimmons@example.com,10

In [6]:
import torch.utils.data as data_utils
pd.to_numeric(df["sessions"])
sessions_df = pd.DataFrame(df['sessions'])

# creating tensor from session_df
train_tensor = torch.tensor(sessions_df['sessions'].values)

# printing out result
print(train_tensor)

tensor([ 3,  7, 10,  4,  2,  9,  5,  1,  8,  6,  3,  4,  7,  2,  6,  9,  1,  5,
         8, 10,  3,  7,  4,  6,  2,  9,  5,  1,  8, 10,  3,  4,  7,  2,  6,  9,
         1,  5,  8, 10,  3,  7,  4,  6,  2,  9,  5,  1,  8, 10])

In [7]:
# train_loader = data_utils.DataLoader(train_tensor, batch_size=10, shuffle=True)